pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
      - master
      - feature/*
      - bug/*
  tags:
    include:
      - v*

pr:
  branches:
    include:
      - master

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Compile & Test'
  inputs:
    command: custom
    customCommand: 'run rapido-ci -- --location=rapido-modules/rapido-rn-splash-screen'
  condition: eq(variables['Build.Reason'], 'PullRequest')

- script: |
    npm install npmrc -g
    echo "registry=https://registry.npmjs.com/" >> ./.npmrc
    echo "@virtuelabs-io:registry=https://registry.npmjs.com/" >> ./.npmrc
    echo "//registry.npmjs.com/:_authToken=${NPM_TOKEN}" >> ./.npmrc
    cat ./.npmrc
  displayName: 'Publishing Environemnt Setup'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  env:
    NPM_TOKEN: $(NPM_TOKEN)

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: Npm@1
  displayName: 'Publishing package'
  inputs:
    command: custom
    customCommand: 'run rapido-cd -- --location=rapido-modules/rapido-rn-splash-screen'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
