pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
      - master
      - feature/*
      - bug/*
  tags:
    include:
      - v*

pr:
  branches:
    include:
      - master

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Compile & Test'
  inputs:
    command: custom
    customCommand: 'run rapido-ci -- --location=rapido-modules/rapido-rn-splash-screen'
  condition: eq(variables['Build.Reason'], 'PullRequest')

- script: |
    npm install -g npmrc npm-cli-login
    npm-cli-login -u $NPM_USER -p $NPM_PASSWORD -e $NPM_EMAIL
    echo _auth=$NPM_TOKEN >> ~/.npmrc
    echo email=$NPM_EMAIL >> ~/.npmrc
    echo always-auth=true >> ~/.npmrc
    cat ~/.npmrc
    cp ~/.npmrc rapido-modules/rapido-rn-splash-screen
    cat rapido-modules/rapido-rn-splash-screen/.npmrc
  displayName: 'NPM Login'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  env:
    NPM_USER: $(NPM_USER)
    NPM_EMAIL: $(NPM_EMAIL)
    NPM_PASSWORD: $(NPM_PASSWORD)
    NPM_TOKEN: $(NPM_TOKEN)

- task: Npm@1
  displayName: 'Publishing package'
  inputs:
    command: custom
    customCommand: 'run rapido-cd -- --location=rapido-modules/rapido-rn-splash-screen'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
